#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Jackrabit AI
# 2024 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitAI/Library')
import os
import cohere

import DecoratorFunctions as DF
import FileFunctions as FF

@DF.function_trapper
def GetCohere(model,role,input):
    # Read Tokens
    Tokens=FF.ReadTokens()

    client=cohere.ClientV2(api_key=Tokens['Cohere'], timeout=120)
    completion=client.chat(
            model=model,
            messages=[ { "role":"system", "content": role },
                       { "role":"user",   "content": input } ],
            safety_mode="NONE"
        )
    response=completion.message.content[0].text.strip()
    return response

@DF.function_trapper
def main():
    if len(sys.argv)>2:
        model=sys.argv[1]
        role=sys.argv[2]
    else:
        print("A model and intructions must be supplied.")
        sys.exit(0)

    input=sys.stdin.read().replace('\n','\\n').replace('"',"'")

    response=GetCohere(model,role,input)
    print(response)

if __name__=='__main__':
    main()
