#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Jackrabit AI
# 2024 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/JackrabbitAI/Library')
import os
import huggingface_hub

import DecoratorFunctions as DF
import FileFunctions as FF

@DF.function_trapper
def GetHuggingFace(model,role,input):
    # Read Tokens
    Tokens=FF.ReadTokens()

    clientAI=huggingface_hub.InferenceClient(token=Tokens['HuggingFace'])
    completion=clientAI.chat.completions.create(
            model=model,
            messages=[ { "role":"system", "content": role },
                       { "role":"user",   "content": input } ],
            stream=False
        )
    stop=completion.choices[0].finish_reason
    response=completion.choices[0].message.content.strip()
    RawLog(f"HuggingFace/{model}: {str(completion)}")
    return response,stop

@DF.function_trapper
def main():
    if len(sys.argv)>2:
        model=sys.argv[1]
        role=sys.argv[2]
    else:
        print("A model and intructions must be supplied.")
        sys.exit(0)

    input=sys.stdin.read().replace('\n','\\n').replace('"',"'")

    response=GetHuggingFace(model,role,input)
    print(response)

if __name__=='__main__':
    main()
