#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Jackrabit AI
# 2024-2025 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
import random

def main():
    random.seed()
    if len(sys.argv)<3:
        print("Low and high value are required")

    l=int(sys.argv[1])
    h=int(sys.argv[2])

    if h<l:
        l,h=h,l

    print(random.randint(l,h))

if __name__=='__main__':
    main()
