#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
import os

###
### Main code base. Place order on exchange
###

for data in sys.stdin:
    data=data.strip().split(' ')
    while '' in data:
        data.remove('')

    s=','.join(data)
    print(s)
