#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
import os

inlist=[]

###
### Main code base. Place order on exchange
###

nl2sp=False
if len(sys.argv)>1:
    nl2sp=True

data=sys.stdin.read()

if nl2sp:
    data=data.replace('\n\n',' ').replace('\n',' ')

data=data.split('\n')

for d in data:
    x=d.strip()
    if x=='':
        continue
    if x not in inlist:
        inlist.append(x)

for d in inlist:
    print(d)

