#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Jackrabbit AI
# 2024 Copyright © Robert APM Darin
# All rights reserved unconditionally.

# ViewDB — JackrabbitDB curses viewer: FAST, sorted headers, one-time scan

import sys
sys.path.append('/home/JackrabbitAI/Library')
import os

from JackrabbitDB import JackrabbitDB

if len(sys.argv)<2:
    print("A JackrabbitDB database MUST be provided")
    sys.exit(0)

db=JackrabbitDB(sys.argv[1])
print(f"Database verified: {db.VerifyDatabase()}")
print("Packing...")
db.PackDatabase()
print("Done")
