#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
sys.path.append('/home/JackrabbitAI/Library')
import os
import json

import CoreFunctions as CF
import FileFunctions as FF
import WebFunctions as WF

if len(sys.argv)<2:
    print("A memory file is required.")
    sys.exit(1)

memList=FF.ReadFile2List(sys.argv[1])

for item in memList:
    try:
        mem=json.loads(item)
    except Exception as err:
        continue

    text=CF.DecodeUnicode(mem['content'].strip().replace('\\n','\n'))

    print(f"{mem['role']}/{mem['tokens']}\n\n{text}\n")
