#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os
import time
import psutil

def CountProcess(search_term):
    count = 0
    search_term = search_term.lower()
    for proc in psutil.process_iter(['cmdline']):
        try:
            cmdline = ' '.join(proc.info['cmdline']).lower()
            if search_term in cmdline:
                count += 1
        except Exception ass error: # (psutil.NoSuchProcess, psutil.AccessDenied)
            continue
    return count

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <search_term>")
        sys.exit(1)
    term = sys.argv[1]

    result = CountProcess(term)
    while result>os.cpu_count():
        result = CountProcess(term)
        time.sleep(1)
