#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
sys.path.append('/home/JackrabbitAI/Library')
import os

import FileFunctions as FF
import WebFunctions as WF

raw=False
if len(sys.argv)>2:
    if '-raw' in sys.argv:
        sys.argv.remove('-raw')
        raw=True

if len(sys.argv)<2:
    print("Please verify URL...")
    sys.exit(1)

print(WF.html2text(sys.argv[1],raw=raw))

