#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
sys.path.append('/home/JackrabbitAI/Library')
import os

import FileFunctions as FF
import WebFunctions as WF

print(WF.html2text(sys.argv[1]))

